'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class V_1_3_7
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridV137 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridV137 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hiddenId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ddmExeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmExeRate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddmAthlete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmAthlete As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAthelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAthelete As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddmNegFeeling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmNegFeeling As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNegFeelingY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNegFeelingY As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddmNegFeelingE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmNegFeelingE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNegfeelE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNegfeelE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''GridQ5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridQ5 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ddmStExe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmStExe As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtExeTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExeTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddmExeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmExeUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddmRegExe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmRegExe As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtRegExeTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegExeTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddmRegExeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmRegExeUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtRegExeY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegExeY As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddmPerExe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmPerExe As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtExeMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExeMonths As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtExeYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExeYear As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPartiMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartiMonths As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPartiYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartiYears As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddmExeWorkDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmExeWorkDay As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddmExeWorkInteJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmExeWorkInteJob As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddmExeWorkJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddmExeWorkJob As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DLInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DLInterest As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''GridQ15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridQ15 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtPosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPosi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNeg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hiddenv137Id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenv137Id As Global.System.Web.UI.WebControls.HiddenField
End Class
