'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class V_1_2_6
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridV115 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridV115 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblphysicianName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphysicianName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtphysicianName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtphysicianName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblphysicianPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphysicianPhone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtphysicianPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtphysicianPhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblemergencyContactPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblemergencyContactPersonName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtemergencyContactPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemergencyContactPersonName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblemergencyContactPersonPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblemergencyContactPersonPhone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtemergencyContactPersonPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemergencyContactPersonPhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMedicineDrugsAndReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMedicineDrugsAndReason As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMedicineDrugsAndReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicineDrugsAndReason As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPhysicianKnowParticipation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhysicianKnowParticipation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPhysicianKnowParticipation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhysicianKnowParticipation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPhysicalActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhysicalActivity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPhysicalActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhysicalActivity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''GridParq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridParq As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hidden126Id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidden126Id As Global.System.Web.UI.WebControls.HiddenField
End Class
