'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class v_1_6_9
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridV169 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridV169 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hiddenID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtHRDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHRDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRestHr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRestHr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtExeHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExeHR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBpDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRestingBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRestingBP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWeightIB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightIB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHeightIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeightIN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWeightkg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightkg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHeightm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeightm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBCADate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBCADate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBMI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMI As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSKMDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSKMDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMenCest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenCest As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWomenTriceps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWomenTriceps As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMenAbdomen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenAbdomen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWomenSuprailium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWomenSuprailium As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMenThigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenThigh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWomenThigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWomenThigh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMenTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWomenTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWomenTotal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtfatBodyEstimation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfatBodyEstimation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGMDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGMDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAbdomen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbdomen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWaist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWaist As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRaioWH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRaioWH As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSubmitFrm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitFrm As Global.System.Web.UI.WebControls.Button
End Class
